  # Publish all joint states -----------------------------------
scout_mini_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

scout_mini_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25
  velocity_rolling_window_size: 0.1

  # Base frame_id
  base_frame_id: base_link

 # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Husky hardware provides wheel velocities
  estimate_velocity_from_position: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier:  1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0  # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2

# Publish all joint states -----------------------------------
#scout_state_controller:
#  type: joint_state_controller/JointStateController
#  publish_rate: 50

# Joint velocity controllers ---------------------------------
#scout_motor_fr_controller:
#  type: velocity_controllers/JointVelocityController
#  joint: front_right_wheel
#  pid:
#    p: 5.0
#    i: 20.0
#    d: 0.0
#    i_clamp: 100.0

#scout_motor_fl_controller:
#  type: velocity_controllers/JointVelocityController
#  joint: front_left_wheel
#  pid:
#    p: 5.0
#    i: 20.0
#    d: 0.0
#    i_clamp: 100.0

#scout_motor_rl_controller:
#  type: velocity_controllers/JointVelocityController
#  joint: rear_left_wheel
#  pid:
#    p: 5.0
#    i: 20.0
#    d: 0.0
#    i_clamp: 100.0

#scout_motor_rr_controller:
#  type: velocity_controllers/JointVelocityController
#  joint: rear_right_wheel
#  pid:
#    p: 5.0
#    i: 20.0
#    d: 0.0
#    i_clamp: 100.0